### ISSUE TITLE
MobsToEggs not catching

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#57]
Farmers can throw the eggs and it will charge them for "Catching an animal" but it will still say "You failed to catch a <animal>."

This was working 24 hours ago.

**Comment by aligothz** [comment]
I was getting this bug yesterday with withered skeletons, but I was able to catch a cow.  Do you have any more details around what they were trying to catch specifically?

**Comment by taylorhaight** [comment]
I've been trying chickens, pigs, and cows, and even set to 100% chance of catching. Nothing is catching anymore.

**Comment by taylorhaight** [comment]
[17:53:48 ERROR]: Could not pass event EntityDamageByEntityEvent to MobsToEggs v1.7.11
java.lang.LinkageError: loader constraint violation: loader 'MobsToEggs - 1.7.11.jar' @6dd17e6e wants to load class io.lumine.mythic.bukkit.BukkitAPIHelper. A different class with the same name was previously loaded by 'MythicMobs-5.7.0-SNAPSHOT.jar' @55d8e409. (io.lumine.mythic.bukkit.BukkitAPIHelper is in unnamed module of loader 'MythicMobs-5.7.0-SNAPSHOT.jar' @55d8e409, parent loader java.net.URLClassLoader @7e32c033)
        at MobsToEggs - 1.7.11.jar/fyi.sugar.mobstoeggs.events.SpawnEggCreateEvent.onSpawnEggCreate(SpawnEggCreateEvent.kt:69) ~[MobsToEggs - 1.7.11.jar:?]
        at MobsToEggs - 1.7.11.jar/fyi.sugar.mobstoeggs.events.CaptureOutcomeEvent.onOutcome(CaptureOutcomeEvent.kt:24) ~[MobsToEggs - 1.7.11.jar:?]
        at MobsToEggs - 1.7.11.jar/fyi.sugar.mobstoeggs.events.CapsuleCollisionEvent.onCapsuleHitEvent(CapsuleCollisionEvent.kt:112) ~[MobsToEggs - 1.7.11.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor907.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-111-66165f7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-111-66165f7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-111-66165f7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:271) ~[paper-1.21.jar:1.21-111-66165f7]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1203) ~[paper-1.21.jar:1.21-111-66165f7]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1193) ~[paper-1.21.jar:1.21-111-66165f7]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1123) ~[paper-1.21.jar:1.21-111-66165f7]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1086) ~[paper-1.21.jar:1.21-111-66165f7]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1241) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.entity.projectile.ThrownEgg.onHitEntity(ThrownEgg.java:52) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:268) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.entity.projectile.ThrownEgg.onHit(ThrownEgg.java:57) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:233) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:212) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:49) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1291) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:780) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:760) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1805) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1597) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-111-66165f7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by taylorhaight** [comment]
Looks like it's conflicting with MythicMobs

**Comment by aligothz** [comment]
tested this morning after server restart, and it appears to be working correctly now.  validated on blaze, zombie pigmen, cows, but was unable to properly capture wither skeleton.  As such, leaving other bug report open for now.

I also adjusted the catch chance for cows back to 30% like others, and adjusted capture cost on all mobs to $50, as it was prior.
