### ISSUE TITLE
Paint Items Infinite Durability

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#59]
Paint items such as brushes and buckets have infinite durability.

**Comment by Technofied** [comment]
Needs errors/further debugging attached so a report can be made to IA

**Comment by taylorhaight** [comment]
[01:21:31 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v4.0.2-alpha-test-3
java.lang.IllegalArgumentException: Damage cannot exceed max damage
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaItem.setDamage(CraftMetaItem.java:1628) ~[paper-1.21.jar:1.21-124-df3b654]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.nd.k(SourceFile:375) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.eO.e(SourceFile:97) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.eO.f(SourceFile:107) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.eO.a(SourceFile:128) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.eO.a(SourceFile:279) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.eO.a(SourceFile:237) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.dQ.a(SourceFile:92) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.dQ.a(SourceFile:58) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.dZ.i(SourceFile:56) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.eH.a(SourceFile:593) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.dd.a(SourceFile:974) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.eH.b(SourceFile:584) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.nr.d(SourceFile:110) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.eH.a(SourceFile:583) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.eH.a(SourceFile:593) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.es.k(SourceFile:266) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.di.a(SourceFile:174) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar/ia.m.di.k(SourceFile:290) ~[ItemsAdder_4.0.2-alpha-test-3-1722671203269.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-124-df3b654]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:598) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1871) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Technofied** [comment]
LoneDev will need to take a look at this, no idea how long that'll be.

**Comment by Technofied** [comment]
Resolved. :)
